name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: thefrustrateddev/vue-deploy-github-pages@v1.0.0
      with:
        username: 'lgienapp'
        reponame: 'pigments'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
